[package]
name = "js-flexbox-engine"
version = "0.1.0"
authors = ["hoangpq <pquochoang2007@gmail.com>"]
edition = "2018"

[dependencies]
mini-v8 = "0.1.0"
yoga = "0.3.1"
jni = "0.14.0"

[lib]
name = "flexbox"
crate_type = ["cdylib"]
path = "src/main.rs"
