/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Engine */

#ifndef _Included_Engine
#define _Included_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Engine
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Engine_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
